In [1]:
import numpy as np

In [7]:
arry = np.array([1,2,3,4,5])
print(type(arry))
print(arry.shape)
print(arry[0], arry[1], arry[2], arry[3])
arry[3] = 6
print(arry)

<class 'numpy.ndarray'>
(5,)
1 2 3 4
[1 2 3 6 5]


In [9]:
arry1 = np.array([[1, 2, 3], [4, 5, 6]])
print(arry1.shape)
print(arry1[0, 0], arry1[0, 1], arry1[1, 0])

(2, 3)
1 2 4


In [12]:
aArry = np.zeros((2, 10))
print(aArry)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [14]:
bArry = np.ones((5, 2))
print(bArry)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [16]:
cArry = np.full((2, 5), 7)
print(cArry)

[[7 7 7 7 7]
 [7 7 7 7 7]]


In [22]:
# The numpy.eye() method returns an array of shape, R x C, 
# where all elements are equal to zero, except for the kth diagonal, 
# whose values are equal to one.

dArry = np.eye(2, 10, k = 5)
print(dArry)

[[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]]


In [23]:
randNum = np.random.random((2, 2))
print(randNum)

[[0.48690529 0.81619042]
 [0.84731946 0.14922844]]


In [27]:
# ARRAY INDEXING

In [29]:
arry = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arry)
print(arry[1, 3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
8


In [33]:
print(arry)
bArry = arry[:2, 1:3]
print(bArry)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[2 3]
 [6 7]]


In [38]:
print(bArry)
bArry[0, 0] = 77
print(bArry[0, 0])

[[77  3]
 [ 6  7]]
77


In [43]:
arry = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
row1 = arry[1, :]
row2 = arry[1:3, :]
print(row1, row1.shape)
print(row2, row2.shape)

[5 6 7 8] (4,)
[[ 5  6  7  8]
 [ 9 10 11 12]] (2, 4)


In [46]:
cArry = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
col1 = cArry[:, 1]
col2 = cArry[:, 1:3]
print(col1, col1.shape)
print(col2, col2.shape)

[ 2  6 10] (3,)
[[ 2  3]
 [ 6  7]
 [10 11]] (3, 2)


In [61]:
a = np.array(
    [
        [1, 2], 
        [3, 4], 
        [5, 6],
    ]
)
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 0], a[2, 0]]))
print(a[[1, 0], [0, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[1 4 5]
[1 3 5]
[3 2]
[2 2]


In [64]:
aArry = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
print(aArry)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [77]:
b = np.array([0, 2, 0, 1])
print(b)
print(aArry[np.arange(4), b])

[0 2 0 1]
[ 1  6  7 11]


In [79]:
aArry[np.arange(4), b] += 10
print(aArry)

[[11  2  3]
 [ 4  5 16]
 [17  8  9]
 [10 21 12]]


In [83]:
a = np.array([[9, 10], [11, 12], [13, 14]])
index = (a > 11)
print(index)
print(a[index])
print(a[a > 2])

[[False False]
 [False  True]
 [ True  True]]
[12 13 14]
[ 9 10 11 12 13 14]


In [ ]:
## Array Math

In [90]:
x = np.array([[5, 8], [10, 42]], dtype=np.float64)
y = np.array([[6, 6], [7, 8]], dtype=np.float64)
# add operations
print(x + y)
print(np.add(x, y))

[[11. 14.]
 [17. 50.]]
[[11. 14.]
 [17. 50.]]


In [91]:
# substraction operations
print(x - y)
print(np.subtract(x, y))

[[-1.  2.]
 [ 3. 34.]]
[[-1.  2.]
 [ 3. 34.]]


In [92]:
print(x / y)
print(np.divide(x, y))

[[0.83333333 1.33333333]
 [1.42857143 5.25      ]]
[[0.83333333 1.33333333]
 [1.42857143 5.25      ]]


In [95]:
x = np.array([[25, 36], [49, 144]], dtype=np.float64)
print(np.sqrt(x))

[[ 5.  6.]
 [ 7. 12.]]


In [100]:
x = np.array([[1, 2], [5, 6]])
y = np.array([[3, 4], [7, 8]])

v = np.array([9, 10])
w = np.array([11, 12])

# dot product of two arrays
print(np.dot(v, w))

219


In [108]:
print(x, v)
print(np.dot(x, v))

[[1 2]
 [5 6]] [ 9 10]
[ 29 105]


In [103]:
print(np.dot(x, y))

[[17 20]
 [57 68]]


In [111]:
x = np.array([[5, 10], [13, 24]])
print(np.sum(x))
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

52
[18 34]
[15 37]


In [113]:
xMatrix = np.array([[1, 2], [3, 4]])
print(xMatrix)
# transpose of a matrix
print(xMatrix.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [ ]:
## CREATE MATRICES

In [117]:
print(np.zeros(10))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [121]:
print(np.zeros((2,2))) # Notice Tuples

Matrix of zeroes
----------------
[[0. 0.]
 [0. 0.]]


In [123]:
print(np.ones(2))

[1. 1.]


In [126]:
print(np.ones((2,3,2))) # Note matrix dimension specified by Tuples

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [129]:
print(14 + np.ones((3,3)))

[[15. 15. 15.]
 [15. 15. 15.]
 [15. 15. 15.]]


In [133]:
np.empty((2,2))

array([[0., 0.],
       [0., 0.]])

In [144]:
mat1 = np.eye(4, 5, 2) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 5)
[[0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0.]]


In [135]:
np.arange(5)

array([0, 1, 2])

In [137]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [136]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [139]:
np.arange(13,23,3)

array([13, 16, 19, 22])

In [157]:
np.linspace(2, 3, num = 10) ## num is the no of samples to be generated

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

In [ ]:
## Generate Random Number 

In [151]:
print("Random number generation (Uniform distribution)")
print(np.random.rand(2,2))

Random number generation (Uniform distribution)
[[0.79004741 0.96670369]
 [0.49188415 0.38666546]]


In [154]:
print("Normal distribution")
print(np.random.randn(3,3))

Normal distribution
[[ 1.02957979 -2.12244594 -1.85873344]
 [-1.19839796 -1.48581959 -0.33788549]
 [-0.62218854 -1.70928458 -0.05599698]]


In [ ]:
## Reshaping

In [170]:
from numpy.random import randint
a = randint(1,100,30)
print(a)
b = a.reshape(2,3,5)
b
c = a.reshape(6,-19878)
c

[72  1 81 98 36 73 91 76 73 74 89 90  5 99  3 73 13 32 72 82 34 65 96 17
 20 56 86  3 33 72]


array([[72,  1, 81, 98, 36],
       [73, 91, 76, 73, 74],
       [89, 90,  5, 99,  3],
       [73, 13, 32, 72, 82],
       [34, 65, 96, 17, 20],
       [56, 86,  3, 33, 72]])

In [171]:
print ("Shape of a:", a.shape)
print ("Shape of b:", b.shape)
print ("Shape of c:", c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [ ]:
## INDEXING AND SLICING

In [173]:
arr = np.arange(0,6)
print("Array:",arr)

Array: [0 1 2 3 4 5]


In [174]:
print("Element at 5th index is:", arr[5])

Element at 5th index is: 5


In [ ]:
print("Elements from 3rd to 5th index are:", arr[3:6:2])

In [ ]:
print("Elements up to 4th index are:", arr[:4])
arr